vanilla_killsanity = [
    "Kill an Allay (Killsanity)",
    "Kill an Axolotl (Killsanity)",
    "Kill a Bat (Killsanity)",
    "Kill a Bee (Killsanity)",
    "Kill a Blaze (Killsanity)",
    "Kill a Camel (Killsanity)",
    "Kill a Cave Spider (Killsanity)",
    "Kill a Chicken (Killsanity)",
    "Kill a Cod (Killsanity)",
    "Kill a Cow (Killsanity)",
    "Kill a Creeper (Killsanity)",
    "Kill a Dolphin (Killsanity)",
    "Kill a Donkey (Killsanity)",
    "Kill a Drowned (Killsanity)",
    "Kill an Elder Guardian (Killsanity)",
    "Kill an Enderman (Killsanity)",
    "Kill na Endermite (Killsanity)",
    "Kill an Evoker (Killsanity)",
    "Kill a Fox (Killsanity)",
    "Kill a Frog (Killsanity)",
    "Kill a Ghast (Killsanity)",
    "Kill a Glow Squid (Killsanity)",
    "Kill a Goat (Killsanity)",
    "Kill a Guardian (Killsanity)",
    "Kill a Hoglin (Killsanity)",
    "Kill a Horse (Killsanity)",
    "Kill a Husk (Killsanity)",
    "Kill an Iron Golem (Killsanity)",
    "Kill a Llama (Killsanity)",
    "Kill a Magma Cube (Killsanity)",
    "Kill a Mooshroom (Killsanity)",
    "Kill a Mule (Killsanity)",
    "Kill a Panda (Killsanity)",
    "Kill a Parrot (Killsanity)",
    "Kill a Phantom (Killsanity)",
    "Kill a Pig (Killsanity)",
    "Kill a Piglin (Killsanity)",
    "Kill a Piglin Brute (Killsanity)",
    "Kill a Pillager (Killsanity)",
    "Kill a Polar Bear (Killsanity)",
    "Kill a Pufferfish (Killsanity)",
    "Kill a Rabbit (Killsanity)",
    "Kill a Ravager (Killsanity)",
    "Kill a Salmon (Killsanity)",
    "Kill a Sheep (Killsanity)",
    "Kill a Shulker (Killsanity)",
    "Kill a Silverfish (Killsanity)",
    "Kill a Skeleton (Killsanity)",
    "Kill a Skeleton Horse (Killsanity)",
    "Kill a Slime (Killsanity)",
    "Kill a Sniffer (Killsanity)",
    "Kill a Snow Golem (Killsanity)",
    "Kill a Spider (Killsanity)",
    "Kill a Squid (Killsanity)",
    "Kill a Stray (Killsanity)",
    "Kill a Strider (Killsanity)",
    "Kill a Tadpole (Killsanity)",
    "Kill a Trader Llama (Killsanity)",
    "Kill a Tropical Fish (Killsanity)",
    "Kill a Turtle (Killsanity)",
    "Kill a Vex (Killsanity)",
    "Murder a Villager (Killsanity)",
    "Kill a Vindicator (Killsanity)",
    "Murder a Wandering Trader (Killsanity)",
    "Kill a Witch (Killsanity)",
    "Kill a Wither Skeleton (Killsanity)",
    "Kill a Wolf (Killsanity)",
    "Kill a Zoglin (Killsanity)",
    "Kill a Zombie (Killsanity)",
    "Kill a Zombie Horse (Killsanity)",
    "Kill a Zombie Villager (Killsanity)",
    "Kill a Zombified Piglin (Killsanity)"
]